cpus:
- 0
- 2
- 4
- 6
- 8
- 10
- 12
- 14
- 16
- 18
- 20
- 22
- 24
- 26
- 28
log_dir: /tmpfs/experiments/
#n_resas: 0
net_workers:
- dp: DARC
  ip: 192.168.10.50
  is_echo: 0
  port: 6789
network:
  device_id: 0
  eal_init:
  - -n
  - '2'
  - -l
    #- 0, 2, 4, 6, 8, 10, 12, 14, 28, 30
  - 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30
  - --main-lcore
  - 30
  - --file-prefix
  - maxdml
  - -a
  - '0000:18:00.1'
  mac: 'a:b:c:d:e:f' # this is hard coded
requests:
- type: SHORT
- type: LONG
workers:
  number: 14
  type: AFP_MB
