log_dir: '/proj/psp-PG0/maxdml/experiments/'
shremote_cfgs: '/home/maxdml/codeZ/Persephone/Shremote_cfgs'
psp_apps: '/proj/psp-PG0/maxdml/Persephone/build/src/c++/apps/'
clt: '/proj/psp-PG0/maxdml/client/build/src/c++/apps/'
