base_dir: '/usr/local/sosp'
shremote_cfgs: '/psp/Shremote_cfgs'
log_dir: '/tmpfs/experiments/'
psp_apps: '/usr/local/sosp/Persephone/build/src/c++/apps/'
clt: '/usr/local/sosp/client/build/src/c++/apps/'
shenango: '/usr/local/sosp/Persephone/submodules/shenango'
