server:
    addr: clnode194.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
client0:
    addr: clnode193.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
client1:
    addr: clnode184.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
client2:
    addr: clnode202.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
client3:
    addr: clnode192.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
client4:
    addr: clnode214.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
client5:
    addr: clnode195.clemson.cloudlab.us
    log_dir: '{0.dirs.log_dir}'
    dev_num: '0000:18:00.1'
